VenusProtocol/venus-protocol

docs/CONTRIBUTING.md
I propose we add some contribution guidelines to the repo so that both the team and the external contributors can see our rules and follow them.
This PR lists the guidelines how I see it but ofc these are up for discussion – feel free to comment or propose the new rules if you think I've missed something.
=> WIP: Add contribution guidelines

README.md
- Solidity Smart-contracts in venus-protocol are on version: 0.5.16
- machines on MacOS will get the latest version of solidity instead of 0.5.16
- Developer need to checkout homebrew-ethereum project and follow instructions listed to get solc of version 0.5.16
- [ X] I have updated the documentation to account for the changes in the code.
=> solidity compiler installation instructions for macOS

contracts/Governance/GovernorBravoDelegate.sol, contracts/Governance/GovernorBravoInterfaces.sol, contracts/Utils/ECDSA.sol, contracts/XVSVault/XVSStore.sol, contracts/XVSVault/XVSVault.sol, scenario/src/Contract/GovernorBravo.ts, scenario/src/Contract/XVSVault.ts, scenario/src/Event/GovernorBravoEvent.ts, scenario/src/Event/XVSVaultEvent.ts, scenario/src/Value/GovernorBravoValue.ts, spec/scenario/CoreMacros, spec/scenario/GovernorBravo/Admin.scen, tests/Governance/GovernorBravo/CastVoteTest.js, tests/Governance/GovernorBravo/ProposeTest.js, tests/Governance/GovernorBravo/QueueTest.js, tests/Governance/GovernorBravo/StateTest.js, tests/Governance/XVSVaultGovernanceTest.js, tests/XVSVault/xvsVaultTest.js
=> Vault fixes based on the audit feedback

contracts/XVSVault/XVSVaultProxy.sol, contracts/XVSVault/XVSVaultStorage.sol, tests/XVSVault/xvsVaultProxyTest.js
Problem: bscscan can't infer that the proxy is a proxy due to an unusual name for the implementation storage var. This complicates interacting with the contract via bscscan.
Solution: Replace xvsVaultImplementation with just "implementation".
=> Change implementation var name to more conventional

contracts/ComptrollerInterface.sol, contracts/Liquidator.sol, contracts/Utils/ReentrancyGuard.sol, contracts/Utils/WithAdmin.sol, tests/Contracts/ComptrollerHarness.sol, tests/Contracts/LiquidatorHarness.sol, tests/Liquidator/liquidatorHarnessTest.js, tests/Liquidator/liquidatorTest.js
merge the liquidator branch, but since our liquidators should have time switch to new liquidator interface, we won't disable the original liquidating interface for now.
=> merge liquidator branch without disabling liquidating interface on Comptroller

.github/workflows/venus-protocol.yml
Currently we don't run CI upon PRs to develop, but we should since it's our new default branch.
=> Run CI on develop branch

contracts/ComptrollerInterface.sol, contracts/Lens/VenusLens.sol, networks/testnet.json, scenario/src/Contract/VenusLens.ts, script/hardhat/lens/deploy-venus-lens.js, script/hardhat/lens/get-daily-xvs.js, script/hardhat/lens/get-vtoken-balance.js, script/hardhat/lens/verify-venus-lens.js, script/query/lens/get-daily-xvs.js, script/query/lens/get-underlying-price.js, script/query/lens/get-vtoken-balance.js, tests/Lens/VenusLensTest.js
**Clickup with details:** https://app.clickup.com/t/2d92per
1. vTokenMetadata of a vTokenAddress to get dailySupplyXvs, dailyBorrowXvs, venusSupplySpeed, venusBorrowSpeed
enhance Existing function vTokenMetadata to return the 4 new properties in response (struct)
VenusSpeedPerBlock is accessed from Comptroller for a vTokenAddress
venusSpeedPerBlock to be multiplied by blockPerDay to get dailySupplyXvs and dailyBorrowXvs
2. a new function to compute dailyXvs of an account across all markets
Function to get all vTokens from comptroller
compute dailyXvs for each vToken/market
aggregate the dailyXvs across all markets
```
dailyXvsForUser =
sum for all user's supply markets (market.dailyXvsForSuppliers * supplyInUsd(market, user) / market.totalSupplyInUsd)
+
sum for all user's borrow markets …
```
=> VenusLens with function to get dailyXVS for an account and vToken

contracts/Governance/GovernorBravoDelegate.sol, spec/scenario/GovernorBravo/Execute.scen
Problem: Currently it's impossible to withdraw BNB reserves because GovernorBravo requires the money flows to and from the timelock contract to be equal.
Solution: Allow GovernorBravo to withdraw funds from timelock by changing the behavior of the proposal `value` parameter.
With the new upgrade, the proposal parameter `value` would mean the value transferred from the timelock contract, and not the incoming value of the `execute` invocation.
_Note: the modified `MIN_VOTING_PERIOD` constant is technically unrelated to this PR, but this change was introduced on chain during LUNA incident coverage_
=> Allow transferring funds from timelock

contracts/Lens/SnapshotLens.sol, networks/testnet.json, tests/Lens/SnapshotLensTest.js
Enhance SnapshotLens - add isACollateral indicator
1. Previous version of SnapshotLens contract gets the snapshot for account on the assets they are using as a collateral
2. Updated version is to get snapshot for all markets 
3. For market which has bee chosen by user as a collateral, an indicator is to be set to response struct
A Boolean indicator
=> Enhance SnapshotLens - add isACollateral indicator

package.json
Defines hardhat as a peer dependency and removes npx to use local hardhat when running postinstall command
=> Use hardhat as peer dependency

contracts/Comptroller.sol, contracts/ComptrollerStorage.sol, tests/hardhat/Comptroller/pauseTest.ts
**Problem:** In case of any incident, we would like to be able to just pause certain actions rather than the whole protocol.
**Solution:** Add _setActionsPaused function that accepts a list of markets and actions to pause on these markets. Refactor the current approach to pausing to save some Comptroller space.
**Note:** This change is a bit controversial since it does allow pause guardians to temporarily disable repayBorrow and redeem. This might be worrisome for the community, so I propose we discuss this change publicly before upgrading.
=> Fine grained pause control

contracts/Comptroller.sol, contracts/ComptrollerStorage.sol
This PR reverts in case access controls fail, and hides some deprecated storage fields to save space on public getters
=> Optimize comptroller size yet again

contracts/XVSVault/XVSVault.sol, contracts/XVSVault/XVSVaultStorage.sol, contracts/test/XVSVaultScenario.sol, tests/hardhat/XVS/XVSVault.ts
- Added a new state variable `totalPendingWithdrawals` to track pending withdrawals across all users. 
- We calculate and transfer rewards in requestWithdrawal instead executeWithdrawal 
- If a user has unexecuted pending withdrawal after upgrade then then need to execute that before requesting new withdrawals
- Added `afterUpgrade` flag for WithdrawalRequest so that we can handle existing withdrawals correctly and pay rewards in executeWithdrawal.
Resolves #VEN-792
=> [VEN-792] Stop XVS Reward during Cooldown

contracts/Tokens/VAI/VAIController.sol, contracts/Tokens/VAI/VAIControllerStorage.sol, tests/hardhat/VAI/VAIController.ts
This PR adds access control manager to `VAIController` and lets it control the permissions for `setBaseRate`, `setFloatRate`, `setMintCap` methods.
=> [VEN-850] feat: add access control to VAI params

contracts/Tokens/VAI/VAIController.sol, contracts/Tokens/VAI/VAIControllerStorage.sol
The stability fee implementation proposed in [VIP-80](https://app.venus.io/governance/proposal/80) contained a bug leading to incorrect treatment of existing VAI minters. This PR sets initial minter index for those who minted VAI before the stability fee was introduced.
=> fix: set initial stability fee index for past minters

contracts/Liquidator/Liquidator.sol, contracts/test/LiquidatorHarness.sol, hardhat.config.ts
Auditors often report that using too recent compiler versions may lead to facing yet undiscovered bugs. Version 0.8.13 is stable, and the known issues there are not relevant to our contracts. We use 0.8.13 in our other repos, so in addition to security reasons, I'm also making this change for consistency.
=> chore: set liquidator compiler version to more stable

contracts/Comptroller/ComptrollerInterface.sol, contracts/Lens/VenusLens.sol, tests/hardhat/Lens/Rewards.ts
This PR refactors `pendingVenus` function to return more structured data about pendingRewards.
Resolves : VEN-883
=> [VEN-883] refactor pendingVenus()

docgen-templates/common.hbs, docgen-templates/helpers.ts, docgen-templates/properties.ts
This PR updates the doc generation with custom templates used by other repos. Since our current solidity version doesn't support custom tags, the custom tag sections won't render.
=> [VEN-893] refactor: update doc gen templates

contracts/VRTVault/VRTVault.sol, contracts/Vault/VAIVault.sol, contracts/XVSVault/XVSVault.sol, tests/hardhat/XVS/XVSVault.ts
- Adds `claim(address account)` to VRTVault to claim rewards for another account. 
- Adds `claim(address account)` to VAIVault to claim rewards for another account. 
- Adds `claim(address _account, address _rewardToken, uint256 _pid)` to XVSVault to claim rewards for another account.
For `claim(address account)` method in VRTVault and VAIVault we don't need new unit tests as implementation code is same as the `claim()` method
=> [VEN-1099] Unified Claim Reward for Vaults

contracts/Comptroller/Comptroller.sol, contracts/Comptroller/ComptrollerInterface.sol, contracts/Comptroller/ComptrollerStorage.sol, contracts/DelegateBorrowers/SwapDebtDelegate.sol, contracts/Tokens/VTokens/VBep20.sol, contracts/Tokens/VTokens/VToken.sol, contracts/test/EvilXToken.sol, contracts/test/VBNBHarness.sol, contracts/test/VBep20Harness.sol, script/hardhat/fork/vip-99.ts, script/hardhat/fork/vip-framework/index.ts, tests/hardhat/DelegateBorrowers/SwapDebtDelegate.ts, tests/hardhat/Lens/Rewards.ts
This PR adds delegated borrowing feature. It would allow users to delegate their borrowing power to some account. In `DelegateBorrowers/` directory there is an example delegate – it only allows to swap one debt position to another, e.g. by repaying BUSD and borrowing ETH. The conversion is done based on the current oracle price.
The Comptroller contract is currently oversize by 94 bytes, tests are not yet implemented.
=> feat: add delegate borrowing feature

script/hardhat/fork/vip-102.ts
This PR adds simulations for VIP-102 (Gauntlet recommendations for interest rate curves).
* Raise USDC, BUSD, USDT, TUSD, DAI jump multiplier from 1.09 to 2.5
* Update BNB curve (kink 0.75→0.6, multiplier 0.12→0.15, jump multiplier 2.0→3.0)
* Increase BNB reserve factor from 0.2 to 0.25
* Update Cake curve (kink 0.6→0.5, multiplier 0.15→0.2)
=> test: [VEN-1128] add simulations for VIP-102

contracts/XVSVault/XVSVault.sol, tests/hardhat/XVS/XVSVault.ts
Right now if a user has a pending withdrawal before upgrade then the deposit/claim revert due to underflow in calculations. So to get around this the user needs to execute the pending withdrawals first.
The fix is to enhance the experience by blocking claim/deposit call when there is a before upgrade withdrawal request pending and reverting with a proper error message.
=> [VEN-1238] Deny Claim/Deposit for Pending Withdrawal Request

contracts/Comptroller/Comptroller.sol, contracts/Comptroller/ComptrollerInterface.sol, contracts/InterestRateModels/InterestRateModel.sol, contracts/InterestRateModels/JumpRateModel.sol, contracts/Tokens/VTokens/VToken.sol, contracts/Tokens/VTokens/VTokenInterfaces.sol, tests/hardhat/StableRateModel.ts, tests/hardhat/stableRateRebalancing.ts, tests/hardhat/swapBorrowRateMode.ts
****Update stable rate for the user at rebalance condition****
- Functionality to update the stable rate for the user if rebalancing conditions are satisfying and the user tries to borrow for the same token(i.e. user borrowed some tokens and the stable interest rate is not updated as per rebalancing condition). 
- Swap rate mode with amount.
=> [VEN-1055] Update stable rate for the user at rebalance

contracts/Vault/VAIVault.sol, contracts/XVSVault/XVSVault.sol, contracts/XVSVault/XVSVaultStorage.sol, tests/hardhat/VAI/VAIVault.ts, tests/hardhat/XVS/XVSVault.ts
This PR fixes the findings from the Fairyproof audit report. Here's the breakdown of the issues and resolutions:
1. Different txs for transferring the xvs token to the contract and calling updatePendingRewards
Resolution: Won't fix
Rationale: The rewards are distributed in an automated fashion in the Comptroller contract, so it is currently not possible that updatePendingRewards is not called. The provided recommendation sounds reasonable and it could help to prevent "reward swallowing" in case Comptroller code is modified to remove this call. However, it is important to limit the scope of the changes for the upgrade, so we will postpone fixing this for now.
2. Admin's Access Control Can be Recovered
Resolution: Fix provided (burnAdmin function has been removed)
3. Front-running (deposit …
=> [VEN-1425] fix: fairyproof findings for the vaults audit 2023-05

tests/hardhat/Comptroller/accessControl.ts, tests/hardhat/Comptroller/assetListTest.ts, tests/hardhat/Comptroller/comptrollerTest.ts, tests/hardhat/Comptroller/liquidateCalculateAmountSeizeTest.ts, tests/hardhat/Governance/GovernanceBravo/proposeTest.ts, tests/hardhat/Governance/GovernanceBravo/stateTest.ts, tests/hardhat/Unitroller/adminTest.ts, tests/hardhat/Unitroller/unitrollerTest.ts, tests/hardhat/VAI/VAIController.ts, tests/hardhat/XVS/XVSVaultFix.ts
Some of our tests have missing awaits. It has been flagged by linter but as a warning, not as an error. However, dangling promises may cause test suite to succeed when it shouldn't, e.g. missing await before expecting an event would make the test succeed even if the event is not emitted. This PR adds the missing awaits where appropriate.
=> test: fix dangling promises in tests

contracts/XVSVault/XVSVault.sol, contracts/XVSVault/XVSVaultStorage.sol, contracts/test/XVSVaultScenario.sol, tests/hardhat/XVS/XVSVault.ts
This PR adds some safeguards against erasing the information about the users' rewards in case of insufficient reward token amounts in XVSStore.
Due to how the vault works, we have to distribute the accumulated rewards upon every deposit and withdrawal request. This way we make sure that the shares we apply the rewards to are the same. However, if it turns out we don't have enugh funds to pay out due to some reason, we just _erase_ the information about the rewards. This has caused some pain in the past, and (hopefully unlikely) may cause pain in future.
As a simplest mitigation, we could revert the transaction in case of insufficient funding. However, this is a denial of service vector – if Venus fails to deliver rewards, users would not be able to withdraw their funds (the …
=> [VEN-1483]: handle insufficient rewards in the vault

contracts/XVSVault/XVSVault.sol, tests/hardhat/XVS/XVSVault.ts
**Problem:** If a pool is added with alloc points equal to zero, and it is the only pool per reward token, total alloc points would be zero, leading to division by zero error in massUpdatePools. It is not possible to recover by calling `set()` with a different alloc points parameter because `set()` calls massUpdatePools under the hood. This can lead to denial of service because deposits, withdrawals and claims will not be possible either. Misconfiguring a pool using `set()` call can have the same impact if there is no other pool for this reward token.
**Solution:**
1. Forbid adding a pool with zero alloc points. This should never happen because it does not make sense from the business point of view.
2. **Allow** setting zero alloc points for existing pools **if** there is another pool …
=> [VEN-1577]: forbid zero alloc points in XVSVault

contracts/Swap/RouterHelper.sol, contracts/Swap/SwapRouter.sol, contracts/Swap/interfaces/CustomErrors.sol, contracts/Swap/interfaces/IPancakeSwapV2Router.sol, contracts/Swap/interfaces/IVBNB.sol, contracts/Swap/lib/PancakeLibrary.sol, contracts/Swap/lib/TransferHelper.sol, script/deploy/swapRouter.js, tests/hardhat/Fork/swapTest.ts, tests/hardhat/Swap/swapTest.ts
This PR resolves the OpenZepplein audit and fixes that we accepted to fix.
Audit fixes:
- L-01. Missing Docstring
- L-02. Locked BNB in contract
- N-01. Misleading Docstirng
- N-02. Naming can be improved
- N-04 Confusing Use of ETH and BNB in Comments and Function Names
- N-03 Some Convenience Functions Are Missing
-- In N-03 we have added the following methods:
• `swapExactTokensForBNBAndSupply`
• `swapExactTokensForBNBAndSupplyAtSupportingFee`
• `swapTokensForExactBNBAndSupply`
But we cannot implement `swapTokensForExactBNBAndSupplyAtSupportingFee` as  `swapTokensForExactBNBAtSupportingFee` does not exist because to get the amount of the tokens(deflationary) to swap for exactBNB is not possible.
Resolves #
VEN-1571
=>  [VEN-1571]: Fix openZeppelin swap router audit

contracts/Lens/InterestRateModelLens.sol
Correct spelling of return description for `getSimulationResponse`
=> docs: correct spelling

contracts/Liquidator/Liquidator.sol
N-01 Incorrect Docstring
N-02 Improper Use of Named Return Variable
N-03 Using int/uint Instead of int256/uint256
Resolves [VEN-1690]
=> [VEN-1690]: Fix OpenZeppelin audit comments

contracts/Liquidator/Interfaces.sol, contracts/Liquidator/Liquidator.sol, tests/hardhat/Fork/ForceVAIDebtFirstTest.ts, tests/hardhat/Fork/reduceResevesTest.ts
- VEN-1 : added a validation check in `liquidateBorrow()` function to make sure `liquidationIncentiveMantissa` is greater than `treasuryPercent`
- VEN-3 : added a sanity check
- VEN-8 : override the `renounceOwnership` to a empty implementation
Resolves VEN-1745
=> [VEN-1745]: Liquidator Quantstamp audit fixes

contracts/Comptroller/ComptrollerStorage.sol, contracts/Comptroller/Diamond/Diamond.sol, contracts/Comptroller/Diamond/facets/FacetBase.sol, contracts/Comptroller/Diamond/facets/MarketFacet.sol, contracts/Comptroller/Diamond/facets/PolicyFacet.sol, contracts/Comptroller/Diamond/facets/RewardFacet.sol, contracts/Comptroller/Diamond/facets/SetterFacet.sol, contracts/Comptroller/Diamond/facets/XVSRewardsHelper.sol, contracts/Comptroller/Diamond/interfaces/IDiamondCut.sol, contracts/Comptroller/Diamond/interfaces/IMarketFacet.sol, contracts/Comptroller/Diamond/interfaces/IPolicyFacet.sol, contracts/Comptroller/Diamond/interfaces/IRewardFacet.sol, contracts/Comptroller/Diamond/interfaces/ISetterFacet.sol, tests/hardhat/Comptroller/Diamond/accessControl.ts, tests/hardhat/Lens/Rewards.ts
=> [VEN-1795] OZ Diamond Comptroller audit fixes

networks/testnet.json
This PR fixes the address returned for VenusLens in testnet. Address `0x4C97B56d596d5cCc11727c0AD7d171E7F0d5134e` returns empty results for `pendingRewards`.
=> fix: correct testnet VenusLens address

deploy/006-deploy-swaprouter.ts
Problem: The current version of the core pool SwapRouter accepts vBNB as the last argument. The deployment script fails because it doesn't pass this argument to the constructor.
Solution: Add the missing argument.
Required for https://github.com/VenusProtocol/isolated-pools/pull/292
=> fix: add a missing param to SwapRouter deployment script

contracts/Tokens/Prime/Prime.sol, contracts/Tokens/Prime/PrimeLiquidityProvider.sol, tests/hardhat/Prime/Prime.ts, tests/hardhat/Prime/PrimeLiquidityProvider.ts
This PR includes setter functionality for prime token in **PrimeLiquidityProvider**, as both **Prime** and **PrimeLiquidityProvider** takes eachother address as constructor input. So we need to have a setter in one of the contract.
And also the fixed test for **PrimeLiquidityProvider** regarding **releaseFunds**.
=> Setter for Prime Token in PrimeLiquidityProvider

.solhint.json, contracts/Comptroller/ComptrollerStorage.sol, contracts/Comptroller/Diamond/Diamond.sol, contracts/Comptroller/Diamond/facets/FacetBase.sol, contracts/Comptroller/Diamond/facets/MarketFacet.sol, contracts/Comptroller/Diamond/facets/PolicyFacet.sol, contracts/Comptroller/Diamond/facets/RewardFacet.sol, contracts/Comptroller/Diamond/facets/SetterFacet.sol, contracts/Comptroller/Diamond/facets/XVSRewardsHelper.sol, contracts/Comptroller/Diamond/interfaces/IRewardFacet.sol, contracts/Comptroller/Diamond/interfaces/ISetterFacet.sol, contracts/Tokens/VAI/VAIController.sol, contracts/test/ComptrollerHarness.sol, contracts/test/ComptrollerScenario.sol, contracts/test/VAIControllerHarness.sol, tests/hardhat/Comptroller/Diamond/XVSSpeeds.ts, tests/hardhat/Comptroller/Diamond/comptrollerTest.ts
Resolves 
- VEN-1929: force liquidation implementation in diamond Comptroller architecture
=> [VEN-1929]: force liquidation functionality in diamond implementation of comptroller

contracts/Comptroller/Diamond/DiamondConsolidated.sol
Resolves VEN-2032
This way we'll be able to generate an ABI file, and the TS types, to interact with every functions and getters in the Comptroller contract
=> [VEN-2032]: add contract with the consolidated interface of the Comptroller Diamond

contracts/Liquidator/BUSDLiquidator.sol, contracts/Liquidator/Interfaces.sol, contracts/Liquidator/Liquidator.sol, contracts/Liquidator/approveOrRevert.sol, contracts/Liquidator/constants.sol, contracts/Liquidator/zeroAddress.sol, tests/hardhat/Fork/BUSDLiquidator.ts, tests/hardhat/Fork/utils.ts, tests/hardhat/fixtures/ComptrollerWithMarkets.ts
This PR adds a custom mechanism for BUSD liquidations. Only BUSD liquidator contract will be allowed to liquidate BUSD borrows. To reduce the potential impact of this change, we will not upgrade Comptroller or Liquidator contracts. Instead, BUSD liquidator contract will be allowed to pause and unpause liquidating BUSD debts. Between the transactions, BUSD liquidations will be paused, as far as Comptroller is concerned.
Once a liquidation is triggered in the BUSD liquidator contract, it would:
1. Unpause the liquidations in the Comptroller
1. Transfer BUSD from the sender and approve the Venus Liquidator contract
1. Perform a liquidation
1. Distribute the seized collateral, including the liquidation incentive, according to a custom distribution scheme, configured by Governance
=> [VEN-2005]: BUSD Liquidator

tests/hardhat/Fork/BUSDLiquidator.ts, tests/hardhat/Fork/utils.ts, tests/hardhat/fixtures/ComptrollerWithMarkets.ts
Related to VEN-2005
* Recover lost imports in commit 2538f339280326423f8f1961284d9c0da5ffdb8f
* Fix local execution of the tests at `tests/hardhat/Fork/BUSDLiquidator.ts`. When FORK is disabled, three tests failed due to small differences in the expected balances after the liquidations. The fix uses zero rate model to prevent new interest accruals (regardless of the automine mode).
=> [VEN-2005]: fix BUSDLiquidator tests

contracts/Admin/VBNBAdmin.sol, contracts/Comptroller/Diamond/facets/MarketFacet.sol, contracts/Comptroller/Diamond/facets/PolicyFacet.sol, contracts/Comptroller/Diamond/facets/RewardFacet.sol, contracts/Comptroller/Diamond/facets/SetterFacet.sol, contracts/Comptroller/Diamond/facets/XVSRewardsHelper.sol, contracts/Lens/ComptrollerLens.sol, contracts/Lens/SnapshotLens.sol, contracts/Tokens/VAI/VAIController.sol, contracts/Tokens/VTokens/VBep20.sol, contracts/Tokens/VTokens/VBep20Delegate.sol
To make the contracts compile for the subgraph tests we have to patch some clashing contract names which requires named imports. When preparing that patch, errors started to appear that lead me to discover that variables are being imported through files where they are not defined.
I was able to resolve those errors by making the imports from the files where the variables were defined.
This PR updates VToken and related imports to be named and direct from the files where they are defined
=> refactor: make imports explicit and direct

contracts/Comptroller/ComptrollerStorage.sol, contracts/Comptroller/Diamond/Diamond.sol, contracts/Comptroller/Diamond/facets/FacetBase.sol, contracts/Comptroller/Diamond/facets/PolicyFacet.sol, contracts/Comptroller/Diamond/facets/SetterFacet.sol, contracts/Comptroller/Diamond/interfaces/IRewardFacet.sol, contracts/Comptroller/Diamond/interfaces/ISetterFacet.sol, tests/hardhat/Comptroller/Diamond/comptrollerTest.ts
**Problem:** Sometimes it is useful to liquidate an individual borrower even if the account doesn't have a shortfall. One example may be the BNB exploiter position that, although is healthy, requires constant monitoring despite being disabled on the underlying blockchain level. Other examples may include positions of other individuals that the Governance deems unwanted to Venus, e.g. the accounts of those who have caused shortfalls in the past.
**Solution:** Implement a mechanism similar to forced liquidations that would allow Venus Governance to switch off liquidity checks for a certain account in a certain market.
**Note** that forced liquidations enabled for a user does not prohibit further borrows, i.e. the account being force-liquidated in a certain market can still borrow funds in …
=> [VEN-2142]: add forced liquidations for individual accounts

deploy/005-update-governance.ts
=> chore: ensure string var interacting with ethers.getContractAt

.env.example, .eslinttsconfigrc, README.md, hardhat.config.ts, hardhat.config.zksync.ts, script/deploy/swapRouter.js, tests/hardhat/Fork/BUSDLiquidator.ts, tests/hardhat/Fork/ForceVAIDebtFirstTest.ts, tests/hardhat/Fork/VAIControllerUpgrade.ts, tests/hardhat/Fork/VAIVaultUpgrade.ts, tests/hardhat/Fork/VRTVaultUpgrade.ts, tests/hardhat/Fork/VTokensUpgrade.ts, tests/hardhat/Fork/XVSVaultUpgrade.ts, tests/hardhat/Fork/XVSVaultUpgradeTimeManager.ts, tests/hardhat/Fork/comptrollerXVSAddressesUpgrade.ts, tests/hardhat/Fork/diamondTest.ts, tests/hardhat/Fork/reduceResevesTest.ts, tests/hardhat/Fork/swapTest.ts, tests/hardhat/Fork/utils.ts, tests/hardhat/Fork/vBNBAdmin.ts, tests/hardhat/Fork/vTokenACMUpdates.ts, tests/hardhat/Fork/vTokenRedeemUpgrade.ts, tests/hardhat/Fork/vrtStopRewards.ts, tests/hardhat/XVS/XVSVaultFix.ts, tsconfig.json, type-extensions.ts, yarn.lock
Fixes some issues with fork tests
Adds support for forked deployments
=> Add fork deployments
