contracts/VenusPriceOracle.sol

Venus Price Oracle Implementation

Venus Price Oracle Implementation

---

README.md
contracts/Comptroller.sol
contracts/ComptrollerInterface.sol
contracts/ComptrollerStorage.sol
contracts/VAIController.sol
contracts/VAIControllerInterface.sol
contracts/VAIControllerStorage.sol
tests/Comptroller/protocolPauseTest.js
tests/Contracts/ComptrollerHarness.sol
tests/Contracts/VAIControllerHarness.sol
tests/Contracts/VAIHarness.sol
tests/Flywheel/FlywheelTest.js
tests/Flywheel/FlywheelVAITest.js
tests/Utils/Venus.js

- VAI mint reward implementation
- Added test cases for VAI mint reward

VAI mint reward implementation, test cases

---

contracts/VAIController.sol
tests/Contracts/ComptrollerHarness.sol
tests/Flywheel/FlywheelTest.js
tests/Flywheel/FlywheelVAITest.js
tests/Utils/Venus.js

Updated reward calculation from user's VAI balance to user's minted VAI amount.

Updated reward calculation for VAI amount

---

contracts/ComptrollerG2.sol
contracts/ComptrollerStorage.sol
scenario/src/Builder/ComptrollerImplBuilder.ts
scenario/src/Contract/Comptroller.ts
scenario/src/ContractLookup.ts
scenario/src/CoreValue.ts
scenario/src/ErrorReporterConstants.ts
scenario/src/Event/ComptrollerEvent.ts
scenario/src/Event/ComptrollerImplEvent.ts
scenario/src/Value/ComptrollerValue.ts
spec/scenario/BorrowCap.scen
spec/scenario/CoreMacros
spec/scenario/Flywheel/Flywheel.scen
spec/scenario/Flywheel/VenusSpeed.scen
spec/scenario/PriceOracleProxy.scen
spec/scenario/Timelock.scen
spec/scenario/Unitroller.scen
spec/sim/0001-venus-distribution-patch/hypothetical_upgrade.scen
tests/Contracts/ComptrollerHarness.sol
tests/Contracts/ComptrollerScenarioG1.sol
tests/Contracts/ComptrollerScenarioG2.sol
tests/Flywheel/FlywheelTest.js
tests/Flywheel/FlywheelVAITest.js
tests/Utils/Venus.js
tests/gasProfiler.js

- Implemented borrow cap
- Implemented venusSpeed per market
- Added comptroller versions and related test cases, scenarios

VIP-4 Implemented borrow cap, venus speed per market, added test cases

---

contracts/VTreasury.sol
tests/treasuryTest.js

- Build treasury Contract
- Implement Testcases for treasury

Add treasury contract & testcases

---

contracts/VTreasury.sol
tests/treasuryTest.js

Add BNB treasury withdraw feature to Treasury Contract and update testcases.

Add BNB treasury withdraw feature to Treasury Contract

---

contracts/VBep20Delegator.sol
contracts/VXvsLikeDelegate.sol
tests/Comptroller/accountLiquidityTest.js
tests/Tokens/xvsLikeTest.js
tests/Utils/Venus.js

- Added xvs like delegator
- Updated vbep20delegator

Added xvs like delegator, Updated vbep20delegator

---

contracts/Comptroller.sol
tests/Comptroller/protocolPauseTest.js

- Added pause guardian admin function

Added pause guardian admin function

---

contracts/AggregatorV2V3Interface.sol
contracts/MockV3Aggregator.sol
contracts/VenusChainlinkOracle.sol
tests/Contracts/MockV3Aggregator.sol
tests/Utils/Venus.js
tests/VenusChainlinkOracleTest.js

Here are our feed contract addresses on BSC: https://docs.chain.link/docs/binance-smart-chain-addresses
I can deploy the contract to testnet for you and set the addresses before handing over admin if you like.

Add Chainlink oracles to Venus

---

contracts/Governance/GovernorBravoDelegator.sol
scenario/src/Builder/GovernorBravoBuilder.ts
scenario/src/Contract/GovernorBravo.ts
scenario/src/Contract/XVSVault.ts
scenario/src/Event/GovernorBravoEvent.ts
scenario/src/Event/XVSVaultEvent.ts
scenario/src/Value/GovernorBravoValue.ts
spec/scenario/CoreMacros
spec/scenario/GovernorBravo/Admin.scen
spec/scenario/GovernorBravo/Cancel.scen
spec/scenario/GovernorBravo/Defeat.scen
spec/scenario/GovernorBravo/Execute.scen
spec/scenario/GovernorBravo/Propose.scen
spec/scenario/GovernorBravo/Queue.scen
spec/scenario/GovernorBravo/Upgrade.scen
spec/scenario/GovernorBravo/Vote.scen
tests/Contracts/GovernorBravoHarness.sol
tests/Contracts/GovernorBravoImmutable.sol
tests/Governance/GovernorBravo/CastVoteTest.js
tests/Governance/GovernorBravo/ProposeTest.js
tests/Governance/GovernorBravo/QueueTest.js
tests/Governance/GovernorBravo/StateTest.js

Tests in the current vault PR are failing and not exhaustive due to dependencies between the branches we worked on in parallel. This PR fixes the tests:
- Adds lockPeriod to tests and scenarios
- Adds guardian to deployment commands
- Adds guardian scenarios
- Adds JS test cases for the vault-based governance (PR #76).

Fix Governor Bravo tests & scenarios

---

tests/Contracts/ComptrollerHarness.sol
tests/Contracts/LiquidatorHarness.sol
tests/Liquidator/liquidatorHarnessTest.js
tests/Liquidator/liquidatorTest.js

- LiquidatorHarness contract for tests
- Tests for liquidator functions

Liquidator Contract - tests

---

contracts/XVSVault/XVSVault.sol
contracts/XVSVault/XVSVaultStorage.sol
hardhat.config.js
package.json
script/hardhat/simulations/vaultUpgrade.js
script/hardhat/utils/misc.js
script/hardhat/utils/timeTravel.js
script/hardhat/utils/voting.js
tests/XVSVault/xvsVaultTest.js
yarn.lock

The previous implementation of the vault contained an error that led to incorrect computation of the voting power. This PR fixes the issue and resets the delegates and voting power data.

Fix voting power in the vault

---

script/hardhat/vips/vip50.js

We want to ensure that the governance migration works smoothly, and no errors will occur along the way.
This PR adds a hardhat script that simulates Bravo deployment, VIP-50 and post-migration _initiate call.

VIP-50 Governance upgrade simulation

---

contracts/Tokens/VRT.sol
contracts/Utils/Owned.sol
contracts/Utils/Tokenlock.sol

Change Detail:
New directory for Tokens is added under contracts
VRT Token contract code
Owned and Tokenlock contracts are added under Utils - as a common/shared contracts

VRT Token Contract

---

script/hardhat/simulations/treasuryWithdraw.js
script/hardhat/utils/misc.js

A simple simulation of withdrawing fund from treasury, making sure everything is good
Resolves #

add simulation script for withdrawing fund from treasury

---

contracts/Liquidator.sol
tests/Liquidator/liquidatorTest.js

This PR fixes a couple of minor code style issues and typos in the liquidator contract based on the comptroller audit results we received

Liquidator cleanup

---

contracts/Comptroller.sol
tests/Comptroller/comptrollerTest.js
tests/Flywheel/FlywheelTest.js

The audits revealed several minor issues with the current comptroller code. This PR addresses these issues. It does not introduce any new functionality.
Originally authored by @RoseRompkxm

Address comptroller audit feedback

---

contracts/Comptroller.sol
contracts/Liquidator.sol
contracts/PriceOracle.sol
contracts/test/ComptrollerHarness.sol
package.json
scenario/src/Contract/Comptroller.ts
scenario/src/Contract/ComptrollerLens.ts
scenario/src/CoreEvent.ts
scenario/src/Event/ComptrollerEvent.ts
spec/scenario/BreakLiquidateVAI.scen
spec/scenario/CoreMacros
tests/Comptroller/comptrollerTest.js
tests/Liquidator/liquidatorTest.js
yarn.lock

This PR:
* fixes the test suite that started to fail after next comptroller upgrade
* makes it possible to omit the liquidator contract address
* addresses minor issues in Comptroller and Liquidator contracts

Fix scenario tests & address minor audit issues

---

contracts/VenusChainlinkOracle.sol
tests/VenusChainlinkOracleTest.js

We should add a validation process for the price fetched from Chainlink oracle, as additional protection under the unexpected conditions, like LUNA & UST price feed malfunction

add stale price validation when fetching price from Chainlink feed

---

contracts/Lens/VenusLens.sol
hardhat.config.ts
networks/mainnet.json
networks/testnet.json
scenario/src/Contract/VenusLens.ts
script/hardhat/simulations/claimVenus.js
tests/Lens/VenusLensTest.js

Add a pending venus reward view function to provide an easier for clients to get the pending reward data
Resolves #

add pending reward calculation function on VenusLens

---

CODE_OF_CONDUCT.md
README.md

This PR adds a code of conduct based on [Contributor Covenant](https://www.contributor-covenant.org/version/2/0/code_of_conduct.html).
It also fixes some formatting in the REAMD.md

Add code of conduct and contributing guidelines

---

.github/workflows/venus-protocol.yml
Dockerfile
hardhat.config.ts
helpers/utils.ts
package.json

This PR is a continuation of our work on migrating to hardhat. It adds typechain mappings generation to hardhat config, adds the missing imported file and updates the Dockerfile to run hardhat compilation instead of saddle compilation.

Fix hardhat config & tests

---

contracts/Lens/VenusLens.sol
networks/mainnet.json

exclude vUST and vLUNA from dailyXVS computation

BugFix for VenusLens - exclude vUST and vLUNA from dailyXVS computation

---

Dockerfile
contracts/Comptroller.sol
tests/Flywheel/FlywheelTest.js

See the commit messages for details

Optimize XVS claims and blacklist XVS claimers

---

contracts/Comptroller.sol
tests/hardhat/Comptroller/accessControl.ts
tests/hardhat/Comptroller/comptrollerTest.ts
tests/hardhat/Comptroller/pauseTest.ts

This PR addresses the issues raised during the release audit

ACM release audit fixes

---

contracts/Comptroller.sol
contracts/VAIController.sol
contracts/VAIControllerStorage.sol
contracts/test/VAIControllerHarness.sol
tests/hardhat/VAI/VAIController.ts

1. Mint VAI based on weighted supply
2. VAI Mint Cap
Resolves #

VAI Minting

---

tests/Flywheel/FlywheelTest.js
tests/hardhat/Comptroller/accessControl.ts
tests/hardhat/Comptroller/comptrollerTest.ts

chore: :shirt:

---

.github/workflows/venus-protocol.yml
contracts/Governance/GovernorBravoDelegate.sol
contracts/Lens/VenusLens.sol

Adds nat spec for VenusLens and edits natspec for governorBravo

Add edit nat spec

---

.eslinttsconfigrc
.gitignore
docgen-templates/common.hbs
docgen-templates/helpers.ts
hardhat.config.ts

- Moves doc generation to a dir that is not committed
- Adds gitbook hint to common template for dev notes

feat: customize docgen

---

contracts/VAIController.sol
contracts/VenusChainlinkOracle.sol
tests/hardhat/VAI/VAIController.ts

Vai Audit Fixes

---

contracts/Liquidator.sol
tests/hardhat/Liquidator/restrictedLiquidations.ts

Minor natspec updates for clarity and readability

docs: update liquidator natspec

---

contracts/Lens/XVSStakingLens.sol
deploy/000-lenses.ts

1. Get Staked XVSAmount of a user
2. Get PendingWithdrawal amount - from Staked XVS  of a user

XVSStakingLens - get Staked XVS Details of an Account

---

contracts/Comptroller/Comptroller.sol
contracts/Comptroller/ComptrollerStorage.sol
contracts/test/ComptrollerHarness.sol
contracts/test/ComptrollerScenario.sol
hardhat.config.ts
tests/hardhat/Comptroller/XVSSpeeds.ts
tests/hardhat/Comptroller/assetListTest.ts
tests/hardhat/Comptroller/comptrollerTest.ts

This PR contains the changes related to the XVS speeds for borrowers and suppliers. Detailed analysis and required changes are explained in this **[doc](https://docs.google.com/document/d/13LH5hbWbM2Thh8MK3dOPssfkEp0V7szI8ArzUDrW9Q8/edit#heading=h.ouzun9elli9u).**

[VEN-797] Fix: XVS accruel

---

contracts/Lens/ComptrollerLens.sol
contracts/Lens/VenusLens.sol

Update nat spec and organize lens entities within the contract

Organize venus lens

---

package.json

Bump to version to latest release 0.5.0

chore: bump version to 0.5.0

---

contracts/Comptroller/ComptrollerInterface.sol
contracts/Lens/VenusLens.sol

Updated venusLens after setting seprate speeds for supply and borrow: Changed VenusSpeeds to VenusSupplySpeeds and venusBorrowSpeeds.

Changed venusSpeeds to venusSupplySpeeds and venusBorrowSpeeds.

---

.solhint.json
contracts/Tokens/VTokens/VBNB.sol
contracts/Tokens/VTokens/VBep20.sol
contracts/Tokens/VTokens/VBep20Delegator.sol
contracts/Tokens/VTokens/VBep20Immutable.sol
contracts/Tokens/VTokens/VToken.sol
contracts/Tokens/VTokens/VTokenInterfaces.sol

Adds linting ordering and orders entities
Edits nat spec for clarity and per guidelines

[VEN-747] Edit nat spec and order vtoken contracts

---

contracts/XVSVault/XVSVault.sol
contracts/XVSVault/XVSVaultStorage.sol
contracts/test/XVSVaultScenario.sol
hardhat.config.ts
tests/hardhat/XVS/XVSVaultFix.ts
yarn.lock

This PR redefines the structure of the struct in vault storage.
```
struct WithdrawalRequest {
uint256 amount; // no changes
uint128 lockedUntil; // old variable, reducing the storage allocated to 128, that should be enough
uint128 afterUpgrade; // new variable, using the 128 bits of the original slot, that should be zero in the legacy data
} 
```
Resolves #

Fix Implementation of vault Storage

---

script/hardhat/fork/vip-101.ts

Recommendations to include in the VIP:
Lower collateral factor of SXP from 35% to 30%.
Lower collateral factor of TRXOLD from 60% to 50%.
Raise collateral factor of TRX (new) from 0% to 10%.
Raise borrow cap of TRX (new) from 100,000 to 200,000.
Raise supply cap of TRX (new) from 180,000 to 300,000.
Raise borrow cap of ETH from 28,740 to 40,000 tokens.

[VEN-1133] VIP-101 Simulation

---

contracts/Swap/RouterHelper.sol
contracts/Swap/SwapRouter.sol
contracts/Swap/interfaces/IPancakeSwapV2Router.sol
contracts/Swap/interfaces/IVBNB.sol
tests/hardhat/Fork/swapTest.ts
tests/hardhat/Swap/swapTest.ts

[VEN-1131] Added methods for repay with bnb

---

script/hardhat/fork/vip-102.ts
script/hardhat/fork/vip-103.ts

This PR contain simulation of :
VIP-103 Gauntlet Rrecommendations
TRXOLD. Conservative: Decrease CF to 0.30
TRX. Aggressive:
> Increase CF to 0.40
>       Increase Borrow Cap to 4,000,000
>       Increase Supply Cap to 5,000,000
SXP. Lower SXP’s collateral factor to 0.25
USDC. Increase borrow cap to 124,700,000 
USDT. Increase borrow cap to 245,500,000

[VEN-1224] vip-103 simulation

---

.github/workflows/venus-protocol.yml
Dockerfile
README.md

- Update readme to remove reference to swipewallet 
- Remove docker entrypoint
- Use yarn exclusively in container
Resolves #229

Update docker readme and entrypoint

---

script/hardhat/fork/vip-104.ts
script/hardhat/fork/vip-104/comptroller.json
script/hardhat/fork/vip-framework/index.ts
script/hardhat/fork/vip-framework/utils.ts

TRXOLD: Decrease CF to 0.20 (conservative)
TRX: (aggressive)
* Increase CF to 0.45
* Increase Borrow Cap to 8,000,000
* Increase Supply Cap to 10,000,000
DAI: Increase borrow cap to 7,500,000 (from 7 millions)
SXP: lower collateral factor to 17.5%
Resolves #

[VEN-1266] VIP simulations for Gauntlet recommendations week March 27

---

contracts/Tokens/VTokens/VBep20.sol
contracts/Tokens/VTokens/VToken.sol
contracts/test/EvilXToken.sol
contracts/test/VBNBHarness.sol
contracts/test/VBep20Harness.sol

This PR contains the stable rate borrow Functionality
**Modify Borrow Functionality**
- Functionality to take borrow on a stable interest rate.
- Update all the states after borrowing at a Stable rate

[VEN-1049] Modify Borrow Functionality

---

contracts/Comptroller/Comptroller.sol
contracts/Comptroller/ComptrollerInterface.sol
contracts/InterestRateModels/InterestRateModel.sol
contracts/InterestRateModels/JumpRateModel.sol
contracts/Tokens/VTokens/VToken.sol
contracts/Tokens/VTokens/VTokenInterfaces.sol
tests/hardhat/StableRateModel.ts
tests/hardhat/stableRateRebalancing.ts
tests/hardhat/swapBorrowRateMode.ts

****Rebalancing script for off-chain****
- Rebalancing conditions for the stable rate borrow.
- Tests for user to take borrow at both rates at a time.

[VEN-1054]Rebalancing script for off-chain

---

contracts/Comptroller/Comptroller.sol
contracts/Comptroller/ComptrollerInterface.sol
contracts/Comptroller/ComptrollerStorage.sol
contracts/InterestRateModels/JumpRateModel.sol
contracts/Tokens/VTokens/VToken.sol
contracts/Tokens/VTokens/VTokenInterfaces.sol
contracts/test/VBep20Harness.sol
tests/hardhat/Lens/Rewards.ts
tests/hardhat/StableRateModel.ts
tests/hardhat/accrueInterest.ts
tests/hardhat/borrowAndRepay.ts
tests/hardhat/liquidate.ts
tests/hardhat/stableRateRebalancing.ts
tests/hardhat/swapBorrowRateMode.ts

This PR contains:
**Modify Liquidation state borrowing**
- Updated other supporting methods which get totalBorrows.
- Added Liquidation tests

[VEN-1051] Modify Liquidation state borrowing

---

contracts/Swap/RouterHelper.sol
contracts/Swap/SwapRouter.sol
contracts/Swap/interfaces/CustomErrors.sol
contracts/Swap/interfaces/IPancakeSwapV2Router.sol
tests/hardhat/Fork/swapTest.ts
tests/hardhat/Swap/swapTest.ts

This PR contains fixes suggested during the Swap audit:
- PVE001: Revisited slippage control for supporting fee tokens.
- PVE002: Improved sanity checks for system parameters.
- Naming consistency in swap router.
- Improved gas efficiency in router helper.

[VEN-1289]: Swap Audit Fixes

---

contracts/VRTVault/VRTVault.sol
contracts/Vault/VAIVault.sol
contracts/XVSVault/XVSVault.sol
tests/hardhat/VRT/VRTVault.ts

PVE-001 In calim function fix in VRTVault
PVE-002 Sanity checks
PVE-003 Fix floating pragmas
Resolves VEN-1325

[VEN-1325] Peckshield vault fix

---

contracts/Swap/RouterHelper.sol
contracts/Swap/SwapRouter.sol
contracts/Swap/interfaces/CustomErrors.sol
contracts/Swap/interfaces/IPancakeSwapV2Router.sol
deploy/006-deploy-swaprouter.ts
package.json
tests/hardhat/Fork/swapTest.ts
tests/hardhat/Swap/swapTest.ts
yarn.lock

Resolves 
- VEN-1320: Make SwapRouter not upgradable.
- VEN-1321: Add missing swap functions related to BNB.

Refactor swap router

---

contracts/Swap/SwapRouter.sol
hardhat.config.ts

[VEN-1380] Optimised swap router to reduce the size under 24 KB

---

contracts/Swap/RouterHelper.sol
contracts/Swap/SwapRouter.sol
contracts/Swap/interfaces/CustomErrors.sol
contracts/Swap/interfaces/IPancakeSwapV2Router.sol
contracts/Swap/interfaces/IVtoken.sol
contracts/Swap/lib/PancakeLibrary.sol
contracts/Swap/lib/TransferHelper.sol
tests/hardhat/Fork/swapTest.ts
tests/hardhat/Swap/swapTest.ts

This PR contains the fixes for SwapRouter:
- PLS-01: INCORRECT FEE AMOUNT WILL CAUSE ALL SWAPS TO FAIL
- PLS-02: INCOMPLETE CHECK
- SRS-02: MISSING CHECKS
- SRS-03: MISSING ZERO ADDRESS VALIDATION
- SWA-01: POTENTIAL REENTRANCY (OUT-OF-ORDER EVENTS)
- RHS-01: CAN USE safeTransfer()
- SRS-04: COMMENTS FOR FUNCTIONS SUPPORTING FEE
- SRS-05: COMMENTS MISSING PARAMETERS
- SRS-06: INCORRECT COMMENT
- PLS-03: INEFFICIENT CHECKS
- SRS-07: CAN USE SINGLE ADDRESS INPUT
- SWA-02: UNCHECKED BLOCKS CAN OPTIMIZE CONTRACT
- SWA-03: CUSTOM ERRORS CAN BE USED

Certik SwapRouter Audit Fixes 

---

package.json
tsconfig.json

This PR will fix the build failure when releasing

ci: resolve hardhat deploy types when compiling typescript

---

.github/workflows/cd.yml
package.json

- Update files included
- Compile types before building

fix: update imports of package files

---

contracts/VRTVault/VRTVault.sol
contracts/Vault/VAIVault.sol
contracts/XVSVault/XVSVault.sol
tests/hardhat/VRT/VRTVault.ts
tests/hardhat/XVS/XVSVault.ts

This PR contains fixes for Quantstamp audit of the vault contracts conducted in May, 2023

[VEN-1483] Fix Quantstamp findings for the vaults, May 2023

---

tests/hardhat/XVS/XVSVault.ts

Problem: The existing test suite for XVSVault is written in "scenario" manner – instead of testing the behavior of individual functions it runs a series of state updates and assertions, joined by a single real-world use-case. While this is useful to ensure the vault behaves as expected in general, it makes it difficult to add new atomic, function-oriented checks to the suite.
Solution: Refactor the test suite, adding atomic checks to each function previously tested in "scenario" manner. Move the most important and complex scenario to a separate "Scenarios" describe block.

test: refactor XVSVault test suite, make tests more atomic

---

tests/hardhat/XVS/XVSVaultFix.ts

One of the vault fork tests was failing after https://github.com/VenusProtocol/venus-protocol/pull/274.
This PR:
* changes the address format to use checksummed addresses – this is what ethers expects
* uses precise BigNumber math for the amount expected in the event
* expicitly allows margin for the reward instead of comparing strings

test: fix the failing fork test

---

contracts/Swap/IRouterHelper.sol
contracts/Swap/RouterHelper.sol
contracts/Swap/SwapRouter.sol
contracts/Swap/interfaces/CustomErrors.sol
contracts/Swap/interfaces/IPancakePair.sol
contracts/Swap/interfaces/IPancakeSwapV2Factory.sol
contracts/Swap/interfaces/IPancakeSwapV2Router.sol
contracts/Swap/interfaces/IVBNB.sol
contracts/Swap/interfaces/IVtoken.sol
contracts/Swap/interfaces/InterfaceComptroller.sol
contracts/Swap/lib/PancakeLibrary.sol
tests/hardhat/Swap/swapTest.ts

This PR resolves hacken audit and fixes that we accepted to fix and increase the code coverage. 
Audit fixes:
- L01. Missing Zero Address Validation
- I01. SPDX License Identifier Not Provided
- I02. Floating Pragma
- I03. Public Functions That Should Be External
Code coverage before changes:
Code coverage after changes:
Resolves
VEN 1562

[VEN-1562]: Fix Hacken findings on SwapRouter

---

docgen-templates/page.hbs

Escape notice when rendering page hbs template

fix: escape notice when rendering page template

---

contracts/Tokens/VTokens/VToken.sol
contracts/Tokens/VTokens/VTokenInterfaces.sol

Adds an accounts total supply to `Mint`, `MintBehalf` and `Redeem` events.

[VEN-1614]: add total supply to mint and redeem events

---

contracts/VRTVault/VRTVault.sol
contracts/Vault/VAIVault.sol
contracts/XVSVault/XVSVault.sol
tests/hardhat/VRT/VRTVault.ts
tests/hardhat/XVS/XVSVault.ts

Resolves VEN-1594, VEN-1597, VEN-1598, VEN-1600 and VEN-1601

[VEN-1592]: Apply mitigations according to the last Certik audit

---

contracts/Liquidator/Liquidator.sol

[VEN-1624]: Liquidator - fix PeckShield findings

---

networks/mainnet.json
networks/testnet.json

[VEN-1579]: add address of the SwapRouter contract to use in the Core pool

---

contracts/Liquidator/Liquidator.sol

[VEN-1642]: Liquidator Certik fixes

---

contracts/Governance/VTreasury.sol
contracts/Liquidator/Interfaces.sol
contracts/Liquidator/Liquidator.sol

Adds contract level natspec for VTreasury and Liquidation contracts
Refactors Liquidation contract so docs build from natspec

Update vTreasury and liquidation contract natspec

---

contracts/Tokens/VAI/VAIController.sol
contracts/Tokens/VAI/VAIControllerStorage.sol
contracts/Tokens/VAI/VAIUnitroller.sol

Refactor VAIComptroller so natspec compiles. Add contract natspec VAIComptroller and Unitroller

Update interfaces so natspec compiles

---

contracts/Liquidator/Liquidator.sol
tests/hardhat/Fork/reduceResevesTest.ts

[VEN-1642]: Certik comments fixed

---

contracts/Lens/ComptrollerLens.sol
contracts/Lens/InterestRateModelLens.sol
contracts/Tokens/VAI/VAIController.sol
contracts/Utils/ErrorReporter.sol

Add natspec for Comptroller Lens and InterestRateModel Lens

docs: add natspec for lens

---

contracts/Liquidator/Interfaces.sol
contracts/Liquidator/Liquidator.sol

[VEN-1658]: catch all return values in function call

---

.github/workflows/ci.yml
package.json
yarn.lock

Fixes hardhat [issue](https://github.com/NomicFoundation/hardhat/issues/3877) downloading the solidity compiler

[VEN-1689] Fix hardhat compile download issue

---

contracts/Tokens/VTokens/VToken.sol
tests/hardhat/EvilXToken.ts
tests/hardhat/Fork/VTokensUpgrade.ts
tests/hardhat/Fork/vTokenACMUpdates.ts
tests/hardhat/VAI/VAIController.ts

Finding 2.1 : Fix Typo
Resolves [VEN-1794]

[VEN-1794]: Fairyproof fixes of Automatic Income allocation August 1

---

contracts/Tokens/VTokens/VBep20.sol
contracts/Tokens/VTokens/VToken.sol
contracts/Tokens/VTokens/VTokenInterfaces.sol
tests/hardhat/Fork/VTokensUpgrade.ts

Certik fixes on Automatic Income Allocation
Resolves #VEN-1845

[VEN-1845]: Certik fixes on AIA

---

.prettierignore
package.json

Remove exports from package.json as they are not correct and not needed

fix: remove exports from package.json

---

contracts/Comptroller/Diamond/Diamond.sol
contracts/Comptroller/Diamond/facets/FacetBase.sol
contracts/Comptroller/Diamond/facets/MarketFacet.sol
contracts/Comptroller/Diamond/facets/PolicyFacet.sol
contracts/Comptroller/Diamond/facets/RewardFacet.sol
contracts/Comptroller/Diamond/facets/SetterFacet.sol
contracts/Comptroller/Diamond/facets/XVSRewardsHelper.sol
tests/hardhat/Comptroller/Diamond/comptrollerTest.ts

Resolves #VEN-1887
Quantstamp audit fix for comptroller diamond proxy

[VEN-1887]: Quantstamp audit fix for comptroller diamond proxy

---

contracts/Comptroller/Diamond/Diamond.sol
contracts/Comptroller/Diamond/facets/FacetBase.sol
contracts/Comptroller/Diamond/facets/MarketFacet.sol
contracts/Comptroller/Diamond/facets/PolicyFacet.sol
contracts/Comptroller/Diamond/facets/RewardFacet.sol
contracts/Comptroller/Diamond/facets/SetterFacet.sol
contracts/Comptroller/Diamond/facets/XVSRewardsHelper.sol
tests/hardhat/Comptroller/Diamond/comptrollerTest.ts

Reverts VenusProtocol/venus-protocol#328

Revert "[VEN-1887]: Quantstamp audit fix for comptroller diamond proxy"

---

.github/workflows/ci.yml
contracts/Tokens/Prime/Prime.sol
contracts/Tokens/Prime/PrimeLiquidityProvider.sol
contracts/Tokens/Prime/PrimeStorage.sol
hardhat.config.ts
tests/hardhat/Prime/Prime.ts
tests/hardhat/Prime/PrimeLiquidityProvider.ts

This PR contains getter for markets in **Prime Token** and fixes regarding **releaseFunds** and **accrueTokens** in **PrimeLiquidityProvider**.

Fix for PrimeLiquidityProvider functions and Prime Token market getter

---

contracts/Tokens/VTokens/VToken.sol
tests/hardhat/Fork/vTokenACMUpdates.ts

4. [Low] Input Validation
Resolves #

[VEN-1949]: Quantstamp audit fix on AIA

---

contracts/test/BEP20.sol
deploy/005-update-governance.ts

Add mock import to create a typechain of governorBravoDelegate contract.

[VEN-1719]: Update imports to create typechain of governance contracts

---

contracts/Governance/VTreasuryV8.sol
hardhat.config.ts

[VEN-2107]: Quantstamp audit fix on VTreasuryV8

---

README.md

[VEN-791]: fix some format issues in the README file

---

.github/workflows/ci.yml
README.md
deployments/bscmainnet.json
deployments/bsctestnet.json

Updates README with deployment information
Organizes deployments by network

refactor: organize deployments in files per network

---

contracts/Comptroller/Diamond/DiamondConsolidated.sol
contracts/test/WBTC.sol
deployments/bscmainnet.json
deployments/bscmainnet/VTreasury.json
deployments/bsctestnet.json
deployments/bsctestnet/VTreasury.json
hardhat.config.ts
package.json
yarn.lock

Adds deployed vTreasury contract to deployments

Add vtreasury deployment

---

.github/workflows/ci.yml
deployments/opbnbmainnet.json
deployments/opbnbmainnet_addresses.json
deployments/opbnbtestnet_addresses.json

[VEN-2191]: add opbnbtestnet and opbnbmainnet to the ci step to extract addresses

---

package.json
yarn.lock

[VEN-1825]: update dependency of the protocol-share package to the stable one

---

contracts/Tokens/VAI/VAIController.sol

Adds natspec for external and public functions on the VAIComptroller

feat: add mising nat spec for public and external functions

---

contracts/Comptroller/Diamond/facets/RewardFacet.sol
contracts/Comptroller/Diamond/interfaces/IRewardFacet.sol
tests/hardhat/Comptroller/Diamond/accessControl.ts
tests/hardhat/Fork/claimRewards.ts

Resolves #VEN-2262
This PR contains functionality for seizing the **XVS** tokens.

[VEN-2262]: Functionality for seizing xvs tokens

---

package.json
yarn.lock

Remove isolated pools dependency that isn't used

fix: remove unused isolated pools dep

---

deploy/006-deploy-psm.ts
deploy/012-deploy-token-redeemer.ts

Refactor script to not use addresses file

fix: fetch normaltimelock from deployments

---

contracts/Tokens/VTokens/legacy/VBep20R1.sol
contracts/Tokens/VTokens/legacy/VTokenInterfaceR1.sol
contracts/Tokens/VTokens/legacy/VTokenR1.sol
contracts/test/ComptrollerMockR1.sol
helpers/deploymentConfig.ts

Add legacy version of VBEP20 Token with legacy event signatures

refactor: add v1 version of comptroller and vToken for event signatures

---

deploy/006-deploy-swaprouter.ts

Fixes build error failing release

fix: fix type error which fails build

---

contracts/Tokens/VTokens/legacy/VTokenInterfaceR1.sol

Add missing import for legacy VToken contract

fix: add missing import

---

tests/hardhat/Fork/TokenRedeemer.ts

chore: fix some comments

---

funding.json
yarn.lock

Add verification for Atlas Optimism

chore: verify repo for Atlas Optimism

---

.github/workflows/cd.yml
.github/workflows/ci.yml

[VEN-3175]: replace the gh action not valid anymore

---

helpers/markets/bscmainnet.ts
helpers/markets/bsctestnet.ts
helpers/markets/hardhat.ts
helpers/markets/index.ts
helpers/tokens/index.ts

This PR fixes typescript errors caused by https://github.com/VenusProtocol/venus-protocol/pull/578

fix: typescript errors in configuration

---

deployments/bscmainnet/JumpRateModel_base25bps_slope367bps_jump20000bps_kink7500bps_bpy42048000.json
deployments/bscmainnet_addresses.json
helpers/markets/bscmainnet.ts

[VPD-96] Risk parameter updates from Chaos Labs

---

contracts/test/WBTC.sol
tests/hardhat/VAI/PegStability.ts
tests/hardhat/integration/index.ts

fix some minor issues in comments

chore: fix some minor issues in comments
